## Student Attendance Analytics with Pandas

In [6]:
import pandas as pd
import numpy as np

#### Section 0: Data Loading

In [8]:
df = pd.read_excel("aiml_attendance.xlsx")
df

,Roll No,Student Name,Subject,Total Classes,Present,Absent,Excused,Attendance %,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
0,4MW24AI001,ABHIJITH,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67%,Critical,4 more,2026-10-09,1
1,4MW24AI002,ABHISHEK KRISHNA P,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67%,Critical,4 more,2026-10-09,1
2,4MW24AI003,ADITYA,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8%,Critical,32 more,2026-09-22,5
3,4MW24AI004,AKSHATA JAKAREDDY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
4,4MW24AI005,ANANYA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
5,4MW24AI006,ANANYASHREE,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
6,4MW24AI007,ANKITA TARANATH MESTA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
7,4MW24AI008,ANVITH S SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,12,0,0,100%,Safe,✓ Met,2026-10-10,0
8,4MW24AI009,APEKSHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
9,4MW24AI010,ARLENE VELORA FERNANDES,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-09,1
10,4MW24AI011,ASHRITHA,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-09,1
11,4MW24AI013,AYESHA REEMAN,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-06,2
12,4MW24AI014,DHANRAJ L POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,6,6,0,50%,Critical,12 more,2026-10-06,2
13,4MW24AI015,DHANYATHA R,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-09,1
14,4MW24AI016,G BHUPATHE,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
15,4MW24AI018,HARSHAL G POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-09,1
16,4MW24AI019,JNANESH . S,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-09,1
17,4MW24AI020,KEERTHAN KRISHNA SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-09,1
18,4MW24AI021,KISHAN J,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-09-29,3
19,4MW24AI022,KUNDAR KASHISH CHANDRA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-10,0
20,4MW24AI023,LAKSHITHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-10,0
21,4MW24AI024,MANEESH SHETTY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
22,4MW24AI025,MANMITHA,Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17%,Critical,28 more,2026-10-06,2
23,4MW24AI026,MAYUR,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-06,2
24,4MW24AI027,MOHAMMED SIMAK,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-06,2
25,4MW24AI028,MOURYA RAJ H N,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-09-22,5
26,4MW24AI029,MUHAMMED NASHIT,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
27,4MW24AI030,NAVYA,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-10-06,2
28,4MW24AI031,PAVITHRA NAYAK,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
29,4MW24AI032,PRAGNYA R,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
30,4MW24AI033,PRAMOD ACHAR,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-10-06,2
31,4MW24AI034,RAJATH H S,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-10-06,2
32,4MW24AI035,RAJATH K K,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,0%,Critical,36 more,Never,12
33,4MW24AI036,RAJU ASHOKA RATHOD,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,0%,Critical,36 more,Never,12
34,4MW24AI037,RAKESH HEGDE,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
35,4MW24AI038,RASHMI,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8%,Critical,32 more,2026-10-06,2
36,4MW24AI039,RITHIN,Data Science & GenAI - 3nd Yr- AIML,12,4,8,0,33%,Critical,20 more,2026-10-06,2
37,4MW24AI041,SANIKA,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-10-06,2
38,4MW24AI042,SHAMANTH K,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-09,1
39,4MW24AI043,SHETTY RASHIK RATHNAKAR,Data Science & GenAI - 3nd Yr- AIML,12,5,7,0,42%,Critical,16 more,2026-10-06,2
40,4MW24AI044,SHODAN B POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-10,0
41,4MW24AI045,SHRAVYA,Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17%,Critical,28 more,2026-09-08,9
42,4MW24AI046,SHREESH A DEVADIGA,Data Science & GenAI - 3nd Yr- AIML,12,12,0,0,100%,Safe,✓ Met,2026-10-10,0
43,4MW24AI047,SHRIYA DEVADIGA,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
44,4MW24AI048,SINCHANA (SUNDARA MADIVALA),Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17%,Critical,28 more,2026-10-06,2
45,4MW24AI049,SINCHANA (MURALI KUPPAYYA MOGAVEERA),Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
46,4MW24AI050,SPOORTHI,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
47,4MW24AI052,SUPRAJA S M,Data Science & GenAI - 3nd Yr- AIML,12,6,6,0,50%,Critical,12 more,2026-10-09,1
48,4MW24AI053,SUPRITHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
49,4MW24AI054,TEJAS,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-06,2
50,4MW24AI055,TRIPTHI H PADMASHALI,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-09,1
51,4MW24AI056,VAMSH,Data Science & GenAI - 3nd Yr- AIML,12,4,8,0,33%,Critical,20 more,2026-10-06,2
52,4MW24AI057,VANDANA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
53,4MW24AI058,VIGNESH ADIGA,Data Science & GenAI - 3nd Yr- AIML,12,7,5,0,58%,Critical,8 more,2026-09-25,4
54,4MW24AI059,VIHAAN S,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67%,Critical,4 more,2026-10-10,0
55,4MW24AI060,YASHASVI K POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
56,4MW24AI061,Raksha,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
57,4MW25AI400,Dhananjay,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-06,2
58,4MW25AI401,Omkar Rane,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8%,Critical,32 more,2026-09-08,9

#### Section 1: Data Inspection

In [9]:
"""Q1. Display the first 10 rows, the shape of the DataFrame, and the data types of each column."""
df = pd.read_excel("aiml_attendance.xlsx")
print("First 10 rows:")
display(df.head(10))
print("Shape (rows, columns):", df.shape)
print("\nColumn data types:")
print(df.dtypes)

First 10 rows:

,Roll No,Student Name,Subject,Total Classes,Present,Absent,Excused,Attendance %,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
0,4MW24AI001,ABHIJITH,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67%,Critical,4 more,2026-10-09,1
1,4MW24AI002,ABHISHEK KRISHNA P,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67%,Critical,4 more,2026-10-09,1
2,4MW24AI003,ADITYA,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8%,Critical,32 more,2026-09-22,5
3,4MW24AI004,AKSHATA JAKAREDDY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
4,4MW24AI005,ANANYA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
5,4MW24AI006,ANANYASHREE,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
6,4MW24AI007,ANKITA TARANATH MESTA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
7,4MW24AI008,ANVITH S SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,12,0,0,100%,Safe,✓ Met,2026-10-10,0
8,4MW24AI009,APEKSHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
9,4MW24AI010,ARLENE VELORA FERNANDES,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-09,1

Shape (rows, columns): (59, 12)

Column data types:
Roll No                   str
Student Name              str
Subject                   str
Total Classes           int64
Present                 int64
Absent                  int64
Excused                 int64
Attendance %              str
Status                    str
Classes Needed (75%)      str
Last Present Date         str
Consecutive Absences    int64
dtype: object

In [10]:
"""Q2. Check for missing values in each column. Identify which columns have null values (especially Last Present Date with "Never") and report the count. """
print("Missing values in each column:")
print(df.isnull().sum())
print("\n'Never' values in Last Present Date:")
print((df["Last Present Date"].astype(str).str.strip().str.lower() == "never").sum())

Missing values in each column:
Roll No                 0
Student Name            0
Subject                 0
Total Classes           0
Present                 0
Absent                  0
Excused                 0
Attendance %            0
Status                  0
Classes Needed (75%)    0
Last Present Date       0
Consecutive Absences    0
dtype: int64

'Never' values in Last Present Date:
2

In [11]:
"""Q3. Rename the columns to snake_case (e.g., Roll No → roll_no, Student Name → student_name, Attendance % → attendance_pct). Display the updated column list."""
import re
def to_snake_case(column):
    column = column.strip().replace("%", "pct")
    column = re.sub(r"[^A-Za-z0-9]+", "_", column)
    return column.strip("_").lower()

df.columns = [to_snake_case(c) for c in df.columns]
print(df.columns.tolist())

['roll_no', 'student_name', 'subject', 'total_classes', 'present', 'absent', 'excused', 'attendance_pct', 'status', 'classes_needed_75pct', 'last_present_date', 'consecutive_absences']

In [12]:
"""Q4. Convert Attendance % from string format (e.g., "64%") to a numeric float column (0.64 or 64.0). Also convert Last Present Date to datetime, handling "Never" as NaT."""
df["attendance_pct"] = (
    df["attendance_pct"].astype(str)
    .str.replace("%", "", regex=False)
    .str.strip()
    .replace("", np.nan)
    .astype(float)
)
df["last_present_date"] = pd.to_datetime(
    df["last_present_date"].replace("Never", pd.NaT),
    errors="coerce"
)
print(df[["attendance_pct", "last_present_date"]].head())
print("Never/missing dates converted to NaT:", df["last_present_date"].isna().sum())

   attendance_pct last_present_date
0            67.0        2026-10-09
1            67.0        2026-10-09
2             8.0        2026-09-22
3            92.0        2026-10-10
4            83.0        2026-10-09
Never/missing dates converted to NaT: 2

#### Section 2: Filtering & Selection

In [13]:
"""Q5. Filter and display all students whose Status is "Critical". Sort them by Attendance % in ascending order."""
critical_students = df[df["status"] == "Critical"].sort_values(
    "attendance_pct", ascending=True
)
display(critical_students)

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75pct,last_present_date,consecutive_absences
32,4MW24AI035,RAJATH K K,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,0.0,Critical,36 more,NaT,12
33,4MW24AI036,RAJU ASHOKA RATHOD,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,0.0,Critical,36 more,NaT,12
2,4MW24AI003,ADITYA,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8.0,Critical,32 more,2026-09-22,5
35,4MW24AI038,RASHMI,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8.0,Critical,32 more,2026-10-06,2
58,4MW25AI401,Omkar Rane,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8.0,Critical,32 more,2026-09-08,9
22,4MW24AI025,MANMITHA,Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17.0,Critical,28 more,2026-10-06,2
41,4MW24AI045,SHRAVYA,Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17.0,Critical,28 more,2026-09-08,9
44,4MW24AI048,SINCHANA (SUNDARA MADIVALA),Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17.0,Critical,28 more,2026-10-06,2
30,4MW24AI033,PRAMOD ACHAR,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25.0,Critical,24 more,2026-10-06,2
37,4MW24AI041,SANIKA,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25.0,Critical,24 more,2026-10-06,2
31,4MW24AI034,RAJATH H S,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25.0,Critical,24 more,2026-10-06,2
25,4MW24AI028,MOURYA RAJ H N,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25.0,Critical,24 more,2026-09-22,5
18,4MW24AI021,KISHAN J,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25.0,Critical,24 more,2026-09-29,3
27,4MW24AI030,NAVYA,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25.0,Critical,24 more,2026-10-06,2
51,4MW24AI056,VAMSH,Data Science & GenAI - 3nd Yr- AIML,12,4,8,0,33.0,Critical,20 more,2026-10-06,2
36,4MW24AI039,RITHIN,Data Science & GenAI - 3nd Yr- AIML,12,4,8,0,33.0,Critical,20 more,2026-10-06,2
39,4MW24AI043,SHETTY RASHIK RATHNAKAR,Data Science & GenAI - 3nd Yr- AIML,12,5,7,0,42.0,Critical,16 more,2026-10-06,2
47,4MW24AI052,SUPRAJA S M,Data Science & GenAI - 3nd Yr- AIML,12,6,6,0,50.0,Critical,12 more,2026-10-09,1
12,4MW24AI014,DHANRAJ L POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,6,6,0,50.0,Critical,12 more,2026-10-06,2
53,4MW24AI058,VIGNESH ADIGA,Data Science & GenAI - 3nd Yr- AIML,12,7,5,0,58.0,Critical,8 more,2026-09-25,4
0,4MW24AI001,ABHIJITH,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67.0,Critical,4 more,2026-10-09,1
1,4MW24AI002,ABHISHEK KRISHNA P,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67.0,Critical,4 more,2026-10-09,1
54,4MW24AI059,VIHAAN S,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67.0,Critical,4 more,2026-10-10,0

In [14]:
"""Q6. Extract all students who have 0 present days (fully absent). List their roll numbers, names, and consecutive absences."""
fully_absent = df[df["present"] == 0]
display(fully_absent[["roll_no", "student_name", "consecutive_absences"]])

       roll_no        student_name  consecutive_absences
32  4MW24AI035          RAJATH K K                    12
33  4MW24AI036  RAJU ASHOKA RATHOD                    12

In [15]:
"""Q7. Using .loc and .iloc, display:
(a) All "Safe" students using .loc
(b) The first 15 rows and columns 2-6 using .iloc """
safe_students = df.loc[df["status"] == "Safe"]
display(safe_students)
#(b)
display(df.iloc[:15, 2:7])

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75pct,last_present_date,consecutive_absences
3,4MW24AI004,AKSHATA JAKAREDDY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92.0,Safe,✓ Met,2026-10-10,0
7,4MW24AI008,ANVITH S SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,12,0,0,100.0,Safe,✓ Met,2026-10-10,0
14,4MW24AI016,G BHUPATHE,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92.0,Safe,✓ Met,2026-10-10,0
15,4MW24AI018,HARSHAL G POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,1
16,4MW24AI019,JNANESH . S,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,1
17,4MW24AI020,KEERTHAN KRISHNA SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,1
21,4MW24AI024,MANEESH SHETTY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92.0,Safe,✓ Met,2026-10-10,0
26,4MW24AI029,MUHAMMED NASHIT,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92.0,Safe,✓ Met,2026-10-10,0
29,4MW24AI032,PRAGNYA R,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92.0,Safe,✓ Met,2026-10-10,0
38,4MW24AI042,SHAMANTH K,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,1
42,4MW24AI046,SHREESH A DEVADIGA,Data Science & GenAI - 3nd Yr- AIML,12,12,0,0,100.0,Safe,✓ Met,2026-10-10,0
43,4MW24AI047,SHRIYA DEVADIGA,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92.0,Safe,✓ Met,2026-10-10,0
45,4MW24AI049,SINCHANA (MURALI KUPPAYYA MOGAVEERA),Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92.0,Safe,✓ Met,2026-10-10,0

,subject,total_classes,present,absent,excused
0,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0
1,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0
2,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0
3,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0
4,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0
5,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0
6,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0
7,Data Science & GenAI - 3nd Yr- AIML,12,12,0,0
8,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0
9,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0
10,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0
11,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0
12,Data Science & GenAI - 3nd Yr- AIML,12,6,6,0
13,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0
14,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0

In [16]:
"""Q8. Find all students whose Consecutive Absences is greater than or equal to 5. Display their name, status, and last present date."""
absent_5_or_more = df[df["consecutive_absences"] >= 5]
display(absent_5_or_more[["student_name", "status", "last_present_date"]])

          student_name    status last_present_date
2               ADITYA  Critical        2026-09-22
25      MOURYA RAJ H N  Critical        2026-09-22
32          RAJATH K K  Critical               NaT
33  RAJU ASHOKA RATHOD  Critical               NaT
41             SHRAVYA  Critical        2026-09-08
58          Omkar Rane  Critical        2026-09-08

### Section 3: Grouping & Aggregation

In [17]:
"""Q9. Group the data by Status and compute: 
a) Count of students 
b) Average attendance %  
c) Maximum consecutive absences"""
status_summary = df.groupby("status").agg(
    student_count=("student_name", "count"),
    average_attendance_pct=("attendance_pct", "mean"),
    max_consecutive_absences=("consecutive_absences", "max")
)
display(status_summary)

          student_count  average_attendance_pct  max_consecutive_absences
status
Critical             23               30.086957                        12
Safe                 13               93.230769                         1
Warning              23               80.565217                         2

In [18]:
"""Q10. Create a new column Attendance Category:
≥ 90% → "Excellent"
75-89% → "Good"
60-74% → "Average"
< 60% → "Poor"
Then use groupby() to count students in each category."""
df["attendance_category"] = pd.cut(
    df["attendance_pct"],
    bins=[-0.001, 60, 75, 90, 100],
    labels=["Poor", "Average", "Good", "Excellent"],
    right=False,
    include_lowest=True
)
df["attendance_category"] = df["attendance_pct"].apply(
    lambda x: "Excellent" if x >= 90 else
              "Good" if x >= 75 else
              "Average" if x >= 60 else "Poor"
)
print(df.groupby("attendance_category", observed=False).size())

attendance_category
Average       3
Excellent    13
Good         23
Poor         20
dtype: int64

In [19]:
"""Q11. Calculate the total number of classes conducted (sum of Total Classes) and the total present/absent counts across all students using .agg()."""
totals = df[["total_classes", "present", "absent"]].agg("sum")
print(totals)

total_classes    708
present          451
absent           257
dtype: int64

In [20]:
"""Q12. Group by Status and use .agg() to find:
a)min, max, and mean of Present
b)sum of Absent"""
present_absent_summary = df.groupby("status").agg(
    present_min=("present", "min"),
    present_max=("present", "max"),
    present_mean=("present", "mean"),
    absent_sum=("absent", "sum")
)
display(present_absent_summary)

          present_min  present_max  present_mean  absent_sum
status
Critical            0            8      3.608696         193
Safe               11           12     11.153846          11
Warning             9           10      9.695652          53

### Section 4: Feature Engineering & Transformation

In [21]:
"""Q13. Create a new column Risk Score using the formula:
Risk Score = (Absent * 0.4) + (Consecutive Absences * 0.6)
Display the top 10 students with the highest risk score."""
df["risk_score"] = (
    df["absent"] * 0.4 + df["consecutive_absences"] * 0.6
)
top_10_risk = df.nlargest(10, "risk_score")
display(top_10_risk[["roll_no", "student_name", "absent","consecutive_absences", "risk_score"]])

,roll_no,student_name,absent,consecutive_absences,risk_score
32,4MW24AI035,RAJATH K K,12,12,12.0
33,4MW24AI036,RAJU ASHOKA RATHOD,12,12,12.0
58,4MW25AI401,Omkar Rane,11,9,9.8
41,4MW24AI045,SHRAVYA,10,9,9.4
2,4MW24AI003,ADITYA,11,5,7.4
25,4MW24AI028,MOURYA RAJ H N,9,5,6.6
35,4MW24AI038,RASHMI,11,2,5.6
18,4MW24AI021,KISHAN J,9,3,5.4
22,4MW24AI025,MANMITHA,10,2,5.2
44,4MW24AI048,SINCHANA (SUNDARA MADIVALA),10,2,5.2

In [36]:
"""Q14. Add a column Classes Needed (Numeric) by extracting the numeric value from the Classes Needed (75%) column (e.g., "5 more" → 5, "✓ Met" → 0)."""
import pandas as pd

col = "Classes Needed (75%)"

df["Classes Needed (Numeric)"] = (
    pd.to_numeric(
        df[col].astype(str).str.extract(r"(\d+)")[0],
        errors="coerce"
    )
    .fillna(0)
    .astype(int)
)

display(
    df[[
        "Student Name",
        "Classes Needed (75%)",
        "Classes Needed (Numeric)"
    ]]
)

,Student Name,Classes Needed (75%),Classes Needed (Numeric)
0,ABHIJITH,4 more,4
1,ABHISHEK KRISHNA P,4 more,4
2,ADITYA,32 more,32
3,AKSHATA JAKAREDDY,✓ Met,0
4,ANANYA,✓ Met,0
5,ANANYASHREE,✓ Met,0
6,ANKITA TARANATH MESTA,✓ Met,0
7,ANVITH S SHERIGAR,✓ Met,0
8,APEKSHA,✓ Met,0
9,ARLENE VELORA FERNANDES,✓ Met,0
10,ASHRITHA,✓ Met,0
11,AYESHA REEMAN,✓ Met,0
12,DHANRAJ L POOJARY,12 more,12
13,DHANYATHA R,✓ Met,0
14,G BHUPATHE,✓ Met,0
15,HARSHAL G POOJARY,✓ Met,0
16,JNANESH . S,✓ Met,0
17,KEERTHAN KRISHNA SHERIGAR,✓ Met,0
18,KISHAN J,24 more,24
19,KUNDAR KASHISH CHANDRA,✓ Met,0
20,LAKSHITHA,✓ Met,0
21,MANEESH SHETTY,✓ Met,0
22,MANMITHA,28 more,28
23,MAYUR,✓ Met,0
24,MOHAMMED SIMAK,✓ Met,0
25,MOURYA RAJ H N,24 more,24
26,MUHAMMED NASHIT,✓ Met,0
27,NAVYA,24 more,24
28,PAVITHRA NAYAK,✓ Met,0
29,PRAGNYA R,✓ Met,0
30,PRAMOD ACHAR,24 more,24
31,RAJATH H S,24 more,24
32,RAJATH K K,36 more,36
33,RAJU ASHOKA RATHOD,36 more,36
34,RAKESH HEGDE,✓ Met,0
35,RASHMI,32 more,32
36,RITHIN,20 more,20
37,SANIKA,24 more,24
38,SHAMANTH K,✓ Met,0
39,SHETTY RASHIK RATHNAKAR,16 more,16
40,SHODAN B POOJARY,✓ Met,0
41,SHRAVYA,28 more,28
42,SHREESH A DEVADIGA,✓ Met,0
43,SHRIYA DEVADIGA,✓ Met,0
44,SINCHANA (SUNDARA MADIVALA),28 more,28
45,SINCHANA (MURALI KUPPAYYA MOGAVEERA),✓ Met,0
46,SPOORTHI,✓ Met,0
47,SUPRAJA S M,12 more,12
48,SUPRITHA,✓ Met,0
49,TEJAS,✓ Met,0
50,TRIPTHI H PADMASHALI,✓ Met,0
51,VAMSH,20 more,20
52,VANDANA,✓ Met,0
53,VIGNESH ADIGA,8 more,8
54,VIHAAN S,4 more,4
55,YASHASVI K POOJARY,✓ Met,0
56,Raksha,✓ Met,0
57,Dhananjay,✓ Met,0
58,Omkar Rane,32 more,32

In [25]:
"""Q15. Using apply() with a lambda function, create a column Attendance Flag that returns:
a)"Defaulter" if attendance < 75%
b)"Safe" otherwise """
df["attendance_flag"] = df["attendance_pct"].apply(lambda x: "Defaulter" if x < 75 else "Safe")
display(df[["student_name", "attendance_pct", "attendance_flag"]])

                            student_name  attendance_pct attendance_flag
0                               ABHIJITH            67.0       Defaulter
1                     ABHISHEK KRISHNA P            67.0       Defaulter
2                                 ADITYA             8.0       Defaulter
3                      AKSHATA JAKAREDDY            92.0            Safe
4                                 ANANYA            83.0            Safe
5                            ANANYASHREE            83.0            Safe
6                  ANKITA TARANATH MESTA            83.0            Safe
7                      ANVITH S SHERIGAR           100.0            Safe
8                                APEKSHA            83.0            Safe
9                ARLENE VELORA FERNANDES            75.0            Safe
10                              ASHRITHA            75.0            Safe
11                         AYESHA REEMAN            75.0            Safe
12                     DHANRAJ L POOJARY            50.0       Defaulter
13                           DHANYATHA R            75.0            Safe
14                            G BHUPATHE            92.0            Safe
15                     HARSHAL G POOJARY            92.0            Safe
16                           JNANESH . S            92.0            Safe
17             KEERTHAN KRISHNA SHERIGAR            92.0            Safe
18                              KISHAN J            25.0       Defaulter
19                KUNDAR KASHISH CHANDRA            83.0            Safe
20                             LAKSHITHA            83.0            Safe
21                        MANEESH SHETTY            92.0            Safe
22                              MANMITHA            17.0       Defaulter
23                                 MAYUR            83.0            Safe
24                        MOHAMMED SIMAK            75.0            Safe
25                        MOURYA RAJ H N            25.0       Defaulter
26                       MUHAMMED NASHIT            92.0            Safe
27                                 NAVYA            25.0       Defaulter
28                        PAVITHRA NAYAK            83.0            Safe
29                             PRAGNYA R            92.0            Safe
30                          PRAMOD ACHAR            25.0       Defaulter
31                            RAJATH H S            25.0       Defaulter
32                            RAJATH K K             0.0       Defaulter
33                    RAJU ASHOKA RATHOD             0.0       Defaulter
34                          RAKESH HEGDE            83.0            Safe
35                                RASHMI             8.0       Defaulter
36                                RITHIN            33.0       Defaulter
37                                SANIKA            25.0       Defaulter
38                            SHAMANTH K            92.0            Safe
39               SHETTY RASHIK RATHNAKAR            42.0       Defaulter
40                      SHODAN B POOJARY            75.0            Safe
41                               SHRAVYA            17.0       Defaulter
42                    SHREESH A DEVADIGA           100.0            Safe
43                       SHRIYA DEVADIGA            92.0            Safe
44           SINCHANA (SUNDARA MADIVALA)            17.0       Defaulter
45  SINCHANA (MURALI KUPPAYYA MOGAVEERA)            92.0            Safe
46                              SPOORTHI            83.0            Safe
47                           SUPRAJA S M            50.0       Defaulter
48                              SUPRITHA            83.0            Safe
49                                 TEJAS            83.0            Safe
50                  TRIPTHI H PADMASHALI            75.0            Safe
51                                 VAMSH            33.0       Defaulter
52                               VANDANA            83.0            Safe
53                         VIGNESH ADIGA            58.0       Defaulter
54                              VIHAAN S            67.0       Defaulter
55                    YASHASVI K POOJARY            83.0            Safe
56                                Raksha            83.0            Safe
57                             Dhananjay            83.0            Safe
58                            Omkar Rane             8.0       Defaulter

In [26]:
"""Q16. Use pd.cut() to bin students into attendance ranges: [0-50, 50-75, 75-90, 90-100] and label them as ["Critical", "Warning", "Good", "Excellent"]."""
df["attendance_range"] = pd.cut(
    df["attendance_pct"],
    bins=[-0.001, 50, 75, 90, 100],
    labels=["Critical", "Warning", "Good", "Excellent"],
    include_lowest=True,
    right=False
)
df["attendance_range"] = pd.cut(
    df["attendance_pct"],
    bins=[-0.001, 50, 75, 90, 100.001],
    labels=["Critical", "Warning", "Good", "Excellent"],
    include_lowest=True,
    right=False
)
display(df[["student_name", "attendance_pct", "attendance_range"]])

                            student_name  attendance_pct attendance_range
0                               ABHIJITH            67.0          Warning
1                     ABHISHEK KRISHNA P            67.0          Warning
2                                 ADITYA             8.0         Critical
3                      AKSHATA JAKAREDDY            92.0        Excellent
4                                 ANANYA            83.0             Good
5                            ANANYASHREE            83.0             Good
6                  ANKITA TARANATH MESTA            83.0             Good
7                      ANVITH S SHERIGAR           100.0        Excellent
8                                APEKSHA            83.0             Good
9                ARLENE VELORA FERNANDES            75.0             Good
10                              ASHRITHA            75.0             Good
11                         AYESHA REEMAN            75.0             Good
12                     DHANRAJ L POOJARY            50.0          Warning
13                           DHANYATHA R            75.0             Good
14                            G BHUPATHE            92.0        Excellent
15                     HARSHAL G POOJARY            92.0        Excellent
16                           JNANESH . S            92.0        Excellent
17             KEERTHAN KRISHNA SHERIGAR            92.0        Excellent
18                              KISHAN J            25.0         Critical
19                KUNDAR KASHISH CHANDRA            83.0             Good
20                             LAKSHITHA            83.0             Good
21                        MANEESH SHETTY            92.0        Excellent
22                              MANMITHA            17.0         Critical
23                                 MAYUR            83.0             Good
24                        MOHAMMED SIMAK            75.0             Good
25                        MOURYA RAJ H N            25.0         Critical
26                       MUHAMMED NASHIT            92.0        Excellent
27                                 NAVYA            25.0         Critical
28                        PAVITHRA NAYAK            83.0             Good
29                             PRAGNYA R            92.0        Excellent
30                          PRAMOD ACHAR            25.0         Critical
31                            RAJATH H S            25.0         Critical
32                            RAJATH K K             0.0         Critical
33                    RAJU ASHOKA RATHOD             0.0         Critical
34                          RAKESH HEGDE            83.0             Good
35                                RASHMI             8.0         Critical
36                                RITHIN            33.0         Critical
37                                SANIKA            25.0         Critical
38                            SHAMANTH K            92.0        Excellent
39               SHETTY RASHIK RATHNAKAR            42.0         Critical
40                      SHODAN B POOJARY            75.0             Good
41                               SHRAVYA            17.0         Critical
42                    SHREESH A DEVADIGA           100.0        Excellent
43                       SHRIYA DEVADIGA            92.0        Excellent
44           SINCHANA (SUNDARA MADIVALA)            17.0         Critical
45  SINCHANA (MURALI KUPPAYYA MOGAVEERA)            92.0        Excellent
46                              SPOORTHI            83.0             Good
47                           SUPRAJA S M            50.0          Warning
48                              SUPRITHA            83.0             Good
49                                 TEJAS            83.0             Good
50                  TRIPTHI H PADMASHALI            75.0             Good
51                                 VAMSH            33.0         Critical
52                               VANDANA            83.0             Good
53                         VIGNESH ADIGA            58.0          Warning
54                              VIHAAN S            67.0          Warning
55                    YASHASVI K POOJARY            83.0             Good
56                                Raksha            83.0             Good
57                             Dhananjay            83.0             Good
58                            Omkar Rane             8.0         Critical

### Section 5: Advanced Analysis

In [27]:
"""Q17. Using pivot_table(), create a summary showing the count of students by Status and Attendance Category (created in Q10)."""
pivot = pd.pivot_table(
    df,
    index="status",
    columns="attendance_category",
    values="student_name",
    aggfunc="count",
    fill_value=0,
    observed=False
)
display(pivot)

attendance_category  Average  Excellent  Good  Poor
status
Critical                   3          0     0    20
Safe                       0         13     0     0
Warning                    0          0    23     0

In [37]:
"""Q18. Identify duplicate student names (e.g., "ANANYA", "DISHA") and display all rows where the base name repeats. Use string manipulation to extract the base name."""
df = pd.read_excel("aiml_attendance.xlsx")
df.columns = df.columns.str.strip()

# Extract base name
df["base_name"] = (
    df["Student Name"]
    .astype(str)
    .str.strip()
    .str.upper()
    .str.extract(r"^([A-Z]+)", expand=False)
)
repeated_bases = df["base_name"].duplicated(keep=False)
display(
    df.loc[
        repeated_bases,
        ["Roll No", "Student Name", "base_name"]
    ].sort_values("base_name")
)

       Roll No                          Student Name base_name
31  4MW24AI034                            RAJATH H S    RAJATH
32  4MW24AI035                            RAJATH K K    RAJATH
44  4MW24AI048           SINCHANA (SUNDARA MADIVALA)  SINCHANA
45  4MW24AI049  SINCHANA (MURALI KUPPAYYA MOGAVEERA)  SINCHANA

In [38]:
""""Q19. Merge this dataset with a hypothetical Student_Details DataFrame containing Roll No, Branch, and Semester. Perform an inner join and display the merged result."""
student_details = pd.DataFrame({
    "Roll No": df["Roll No"].drop_duplicates().head(5).tolist(),
    "branch": ["AIML"] * min(5, df["Roll No"].nunique()),
    "semester": [5] * min(5, df["Roll No"].nunique())
})
merged = pd.merge(df, student_details, on="Roll No", how="inner")
display(merged)

,Roll No,Student Name,Subject,Total Classes,Present,Absent,Excused,Attendance %,Status,Classes Needed (75%),Last Present Date,Consecutive Absences,base_name,branch,semester
0,4MW24AI001,ABHIJITH,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67%,Critical,4 more,2026-10-09,1,ABHIJITH,AIML,5
1,4MW24AI002,ABHISHEK KRISHNA P,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67%,Critical,4 more,2026-10-09,1,ABHISHEK,AIML,5
2,4MW24AI003,ADITYA,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8%,Critical,32 more,2026-09-22,5,ADITYA,AIML,5
3,4MW24AI004,AKSHATA JAKAREDDY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0,AKSHATA,AIML,5
4,4MW24AI005,ANANYA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1,ANANYA,AIML,5

In [44]:
"""Q20. Export the following to separate CSV files:
(a) All "Critical" students
(b) Summary statistics grouped by Status
(c) Top 10 students by Risk Score"""


import pandas as pd

# Load the Excel file
df = pd.read_excel("aiml_attendance.xlsx")
df.columns = df.columns.str.strip()

# Convert numeric columns to numbers
df["Attendance %"] = pd.to_numeric(
    df["Attendance %"].astype(str).str.replace("%", "", regex=False),
    errors="coerce"
)

df["Present"] = pd.to_numeric(df["Present"], errors="coerce").fillna(0)
df["Absent"] = pd.to_numeric(df["Absent"], errors="coerce").fillna(0)
df["Consecutive Absences"] = pd.to_numeric(
    df["Consecutive Absences"], errors="coerce"
).fillna(0)

# (a) Export all Critical students
df[
    df["Status"].astype(str).str.strip().str.lower() == "critical"
].to_csv("critical_students.csv", index=False)

# (b) Summary statistics grouped by Status
summary = df.groupby("Status").agg(
    student_count=("Student Name", "count"),
    average_attendance=("Attendance %", "mean"),
    total_present=("Present", "sum"),
    total_absent=("Absent", "sum"),
    max_consecutive_absences=("Consecutive Absences", "max")
)

summary.to_csv("Status_summary.csv")

# (c) Calculate Risk Score
df["Risk Score"] = (
    df["Absent"] * 0.4
    + df["Consecutive Absences"] * 0.6
)

# Export top 10 students by Risk Score
df.sort_values(
    "Risk Score", ascending=False
).head(10).to_csv("top_10_risk_students.csv", index=False)

print("All three CSV files exported successfully!")

All three CSV files exported successfully!